### ISSUE TITLE
Demo Project ?

### ISSUE THREAD

**Issue by c-michail** [Codrax/Codrut-Animation-Lib#1]
Hello,
  I can't find the demo project.

Thank you

**Comment by Codrax** [comment]
There isn't one. The project is pretty straight forward, there isn't a need for a demo project. Just install the components, and then in thr design editor on a integer property, click thr 3 dots and press "Create integer animation..."

**Comment by c-michail** [comment]
Well you have one in the frontpage that's why i asked. How to animate the form then ?

Thank you

**Comment by Codrax** [comment]
![image](https://github.com/user-attachments/assets/06825726-02f8-4001-a654-8b469d41cf18)
Use this menu. On an integer property of a Form or Control, click the arrow and select "Create Integer Animation"

**Comment by Codrax** [comment]
I've added a demo project showcasing the basic features of the library.
